# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 16:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('reason', models.TextField()),
                ('purpose', models.TextField()),
                ('own_contribution', models.TextField()),
                ('remarks', models.TextField(blank=True)),
                ('internal_remarks', models.TextField(blank=True)),
                ('how_know_WW', models.TextField(blank=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('public', models.BooleanField()),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbwwinkel.State'),
        ),
    ]
