# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 08:34
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('reason', models.TextField()),
                ('purpose', models.TextField()),
                ('own_contribution', models.TextField()),
                ('remarks', models.TextField(blank=True)),
                ('internal_remarks', models.TextField(blank=True)),
                ('how_know_WW', models.TextField(blank=True)),
                ('deadline', models.DateField(blank=True)),
                ('public', models.BooleanField()),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2017, 3, 27, 10, 34, 9, 436797))),
                ('active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('new', 'nieuw'), ('active', 'actief')], default='new', max_length=10)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
