# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 13:09
from __future__ import unicode_literals

from django.db import migrations, models



def add_initial_statuses(apps, schema_editor):

    status = apps.get_model('dbwwinkel','Status')
    status.status = 'new'
    status.save()

class Migration(migrations.Migration):

    dependencies = [
        ('dbwwinkel', '0001_initial'),
    ]

    operations = [
    ]
