# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 08:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbwwinkel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 27, 10, 38, 43, 158425)),
        ),
    ]
