# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 08:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbwwinkel', '0002_auto_20170327_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 27, 10, 43, 58, 493648)),
        ),
        migrations.AlterField(
            model_name='question',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
